export enum DeviceStatus {
	OKAY = 0,
	ALERT = 1,
	WARNING = 2,
	DANGER = 3
}

export enum DeviceSubStatus {
  NONE = 0,
  DEVICE_LOW_BATTERY = 1,
  HEAVY_MACHINERY_NEARBY = 2,
  AIR_DUST = 3,
  AIR_ORGANIC_COMPOUNDS = 4,
  AIR_VENTILATION_FAILURE = 5,
  TEMPERATURE_SPIKE = 6,
  WATER_HAZARD = 7,
  POISON_GAS = 8,
  SEISMIC_ACTIVITY = 9,
  WATER_FLOODING = 10,
  FIRE_HAZARD = 11,
  ELECTRICAL_FAULT = 12
}
